#!/bin/bash

image_name="retrowave-fe"
container_name="${image_name}-1"
network_name="retrowave"

docker rm -f ${container_name}

docker run \
  -d \
  --restart always \
  --name ${container_name} \
  --network ${network_name} \
  --dns-opt 'ndots:1' \
  -p 80:80 \
  --volumes-from retrowave-ui-1 \
  --volumes-from retrowave-fs-1 \
  ${image_name}
